[package]
name = "wasmonkey"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
clap = "*"
failure = "*"
goblin = "*"
lazy_static = "*"
parity-wasm = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
siphasher = "*"
xfailure = "*"
