[package]
name = "wasmonkey"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Patch a WASM object file to replace a set of exported functions with imported functions from another library"
license = "ISC"
homepage = "https://github.com/jedisct1/wasmonkey"
repository = "https://github.com/jedisct1/wasmonkey"
categories = ["webassembly"]

[dependencies]
clap = "*"
failure = "*"
goblin = "*"
lazy_static = "*"
parity-wasm = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
siphasher = "*"
xfailure = "*"
